services:
  icecast:
    image: libretime/icecast:latest
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      ICECAST_SOURCE_PASSWORD: hackme
      ICECAST_ADMIN_PASSWORD: admin
      ICECAST_HOSTNAME: localhost
    volumes:
      - ./icecast.xml:/etc/icecast.xml
